-- Baseline schema for the opendc-web server.
-- Must stay portable between PostgreSQL (production) and H2 (dev/test, with jsonb aliased to
-- json via the JDBC INIT statement): identity primary keys, jsonb documents, timestamp with
-- time zone.

-- handle is the account's name in identifiers other people read: it prefixes every trace the
-- account uploads, so that two people may both call a trace "nightly" without collision. Unlike
-- display_name it is unique and safe to put in a slug.
create table users (
    id bigint generated by default as identity primary key,
    subject varchar(255) not null unique,
    handle varchar(64) not null unique,
    email varchar(255),
    display_name varchar(255) not null,
    plan_tier varchar(32) not null,
    is_admin boolean not null default false,
    created_at timestamp with time zone not null,
    deactivated_at timestamp with time zone
);

-- Every entity the API exposes carries a public_id alongside its primary key. The key stays a
-- bigint so joins and foreign keys stay cheap; the random uuid is what leaves the server.
-- Sequential identifiers in URLs disclose how much the platform holds (create one, read its
-- number) and make any endpoint that ever forgets its authorization check enumerable, which an
-- unguessable id reduces to a survivable mistake.
create table projects (
    id bigint generated by default as identity primary key,
    public_id uuid not null unique,
    name varchar(255) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table project_members (
    id bigint generated by default as identity primary key,
    project_id bigint not null references projects (id) on delete cascade,
    user_id bigint not null references users (id) on delete cascade,
    role varchar(16) not null,
    unique (project_id, user_id)
);

create table access_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id) on delete cascade,
    name varchar(255) not null,
    token_hash varchar(64) not null unique,
    token_prefix varchar(16) not null,
    created_at timestamp with time zone not null,
    last_used_at timestamp with time zone
);

create table topology_templates (
    id bigint generated by default as identity primary key,
    public_id uuid not null unique,
    project_id bigint not null references projects (id) on delete cascade,
    name varchar(255) not null,
    topology jsonb not null,
    topology_hash varchar(64) not null,
    layout jsonb,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index idx_topology_templates_project on topology_templates (project_id);

create table experiments (
    id bigint generated by default as identity primary key,
    public_id uuid not null unique,
    project_id bigint not null references projects (id) on delete cascade,
    name varchar(255) not null,
    spec jsonb not null,
    spec_hash varchar(64) not null,
    scenario_count integer not null default 0,
    estimated_simulation_seconds double precision not null default 0,
    estimated_budget_seconds double precision not null default 0,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    submitted_at timestamp with time zone
);

create index idx_experiments_project on experiments (project_id);

create table experiment_resources (
    id bigint generated by default as identity primary key,
    experiment_id bigint not null references experiments (id) on delete cascade,
    kind varchar(16) not null,
    reference jsonb not null,
    reference_name varchar(255)
);

create index idx_experiment_resources_experiment on experiment_resources (experiment_id);
create index idx_experiment_resources_name on experiment_resources (reference_name);

-- A trace belongs to an account, not to a project: one library per person, usable from every
-- project they can reach.
--
-- origin is the variant, not a nullable owner. A BUILTIN trace ships with the repository and the
-- SDK's registry resolves it, so it has no owner and no stored bytes; an UPLOADED one has both.
-- The check constraint makes that a rule the database enforces rather than a convention the code
-- is trusted to remember.
--
-- slug is what an experiment document references, so it is unique platform-wide: built-ins are
-- bare ("bitbrains-small") and uploads carry their owner's handle ("alice/nightly-2026"). It may
-- be changed only while no experiment references the trace, which is the same rule that governs
-- deleting one -- a submitted experiment's provenance must keep resolving.
create table traces (
    id bigint generated by default as identity primary key,
    public_id uuid not null unique,
    slug varchar(255) not null unique,
    kind varchar(16) not null,
    origin varchar(16) not null,
    owner_id bigint references users (id) on delete cascade,
    description varchar(1024),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint traces_origin_owner check (
        (origin = 'BUILTIN' and owner_id is null) or (origin = 'UPLOADED' and owner_id is not null)
    )
);

create index idx_traces_owner on traces (owner_id);

-- The bytes of a trace, one row per opendc-trace table it is made of: a workload has tasks and
-- fragments, the other kinds a single table each. Naming a part by its table rather than by a
-- position in a fixed set means a kind that later needs a third table is a change to that kind's
-- table list and nothing here.
--
-- A row exists once the object behind it does, so a trace is ready exactly when it has a part for
-- every table its kind names. The object's key is derived from the trace and the table rather than
-- stored: a browser uploading straight to object storage has to be handed a key before anybody has
-- seen the bytes, which rules out addressing them by their own hash.
create table trace_parts (
    id bigint generated by default as identity primary key,
    trace_id bigint not null references traces (id) on delete cascade,
    table_name varchar(64) not null,
    size_bytes bigint not null,
    row_count bigint,
    unique (trace_id, table_name)
);

-- One row per person a trace has been shared with. A grant governs whether the trace appears in
-- their library and whether they may reference it in a new experiment; it says nothing about
-- experiments already submitted, which pin the content hash.
create table trace_grants (
    id bigint generated by default as identity primary key,
    trace_id bigint not null references traces (id) on delete cascade,
    grantee_id bigint not null references users (id) on delete cascade,
    granted_at timestamp with time zone not null,
    unique (trace_id, grantee_id)
);

create index idx_trace_grants_grantee on trace_grants (grantee_id);

create table bag_executions (
    id bigint generated by default as identity primary key,
    experiment_id bigint not null references experiments (id) on delete cascade,
    bag_index integer not null,
    state varchar(16) not null,
    attempt integer not null default 1,
    dispatcher varchar(32),
    parallelism integer not null default 1,
    estimated_seconds double precision not null default 0,
    memory_limit_mb integer,
    time_limit_seconds integer,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    exit_code integer,
    exit_reason varchar(32),
    exit_message text,
    unique (experiment_id, bag_index)
);

create index idx_bag_executions_experiment on bag_executions (experiment_id);

create table run_units (
    id bigint generated by default as identity primary key,
    bag_id bigint not null references bag_executions (id) on delete cascade,
    experiment_id bigint not null references experiments (id) on delete cascade,
    scenario_index integer not null,
    seed bigint not null,
    state varchar(16) not null,
    total_tasks integer not null default 0,
    completed_tasks integer not null default 0,
    result_location varchar(1024),
    unique (experiment_id, scenario_index, seed)
);

create index idx_run_units_experiment on run_units (experiment_id);
create index idx_run_units_bag on run_units (bag_id);

-- cap_kind names the grant ('limited' or 'unlimited') rather than leaving it to be inferred from a
-- null, so an uncapped account is a stated decision. cap_seconds carries the number when limited.
create table budget_windows (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id) on delete cascade,
    period varchar(16) not null,
    used_seconds double precision not null default 0,
    reserved_seconds double precision not null default 0,
    cap_kind varchar(16) not null,
    cap_seconds double precision,
    resets_at timestamp with time zone not null,
    unique (user_id, period)
);

create table invoices (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id) on delete cascade,
    issued_at timestamp with time zone not null,
    amount_eur numeric(10, 2) not null,
    paid boolean not null default false
);

create table estimator_calibration (
    id bigint generated by default as identity primary key,
    dispatcher varchar(32) not null unique,
    sample_count bigint not null default 0,
    overshoot_p95 double precision,
    multiplier double precision not null default 1.0,
    updated_at timestamp with time zone not null
);

-- The workload traces the deployment ships with. Their slugs are bare, with no owner prefix,
-- because they belong to the deployment rather than to a person, and they carry no parts: a named
-- reference resolves under the launcher's trace root, so the bytes come from the repository rather
-- than from object storage.
--
-- The identifiers are written out rather than generated because the generator is spelled
-- differently in each database (random_uuid on H2, gen_random_uuid on PostgreSQL) and this file
-- has to run on both. Fixed ids also mean a built-in keeps the same URL in every deployment.
--
-- kind and origin are upper case because the entity maps them with EnumType.STRING, which matches
-- on the constant's own name. Seeding them lower case parses as no constant at all and fails every
-- read of these rows.
insert into traces (public_id, slug, kind, origin, created_at, updated_at)
values ('6ba7b810-9dad-11d1-80b4-00c04fd430c8', 'bitbrains-small', 'WORKLOAD', 'BUILTIN', current_timestamp, current_timestamp),
       ('6ba7b811-9dad-11d1-80b4-00c04fd430c8', 'surf-week', 'WORKLOAD', 'BUILTIN', current_timestamp, current_timestamp),
       ('6ba7b812-9dad-11d1-80b4-00c04fd430c8', 'surf-month', 'WORKLOAD', 'BUILTIN', current_timestamp, current_timestamp);