-- Baseline schema for the opendc-web server.
-- Must stay portable between PostgreSQL (production) and H2 (dev/test, with jsonb aliased to
-- json via the JDBC INIT statement): identity primary keys, jsonb documents, timestamp with
-- time zone.

-- handle is the account's name in identifiers other people read: it prefixes every trace the
-- account uploads, so that two people may both call a trace "nightly" without collision. Unlike
-- display_name it is unique and safe to put in a slug. A first sign-in holds a placeholder handle
-- (handle_kind PROVISIONAL) until the person chooses one.
create table users (
    id bigint generated by default as identity primary key,
    subject varchar(255) not null unique,
    handle varchar(64) not null unique,
    handle_kind varchar(16) not null,
    display_name varchar(255) not null,
    plan_tier varchar(32) not null,
    is_admin boolean not null default false,
    state varchar(16) not null default 'ACTIVE',
    created_at timestamp with time zone not null,
    deactivated_at timestamp with time zone,
    constraint users_handle_kind check (handle_kind in ('PROVISIONAL', 'CHOSEN')),
    constraint users_state check (
        (state = 'ACTIVE' and deactivated_at is null)
        or (state = 'DEACTIVATED' and deactivated_at is not null)
    )
);

-- Every entity the API exposes carries a public_id alongside its primary key. The key stays a
-- bigint so joins and foreign keys stay cheap; the random uuid is what leaves the server.
-- Sequential identifiers in URLs disclose how much the platform holds (create one, read its
-- number) and make any endpoint that ever forgets its authorization check enumerable, which an
-- unguessable id reduces to a survivable mistake.
create table projects (
    id bigint generated by default as identity primary key,
    public_id uuid not null unique,
    name varchar(255) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table project_members (
    id bigint generated by default as identity primary key,
    project_id bigint not null references projects (id) on delete cascade,
    user_id bigint not null references users (id) on delete cascade,
    role varchar(16) not null,
    unique (project_id, user_id)
);

-- Personal access tokens. Only the SHA-256 of the secret is kept, and it is what a presented token
-- is looked up by. Use is recorded to the hour, as a kind so an unused token is stated, not inferred.
create table access_tokens (
    id bigint generated by default as identity primary key,
    public_id uuid not null unique,
    user_id bigint not null references users (id) on delete cascade,
    name varchar(255) not null,
    token_hash varchar(64) not null unique,
    token_prefix varchar(16) not null,
    created_at timestamp with time zone not null,
    use_kind varchar(16) not null default 'UNUSED',
    last_used_at timestamp with time zone,
    constraint access_tokens_use check (
        (use_kind = 'UNUSED' and last_used_at is null)
        or (use_kind = 'USED' and last_used_at is not null)
    )
);
create index idx_access_tokens_user on access_tokens (user_id);

create table topology_templates (
    id bigint generated by default as identity primary key,
    public_id uuid not null unique,
    project_id bigint not null references projects (id) on delete cascade,
    name varchar(255) not null,
    topology jsonb not null,
    topology_hash varchar(64) not null,
    layout jsonb,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index idx_topology_templates_project on topology_templates (project_id);

create table experiments (
    id bigint generated by default as identity primary key,
    public_id uuid not null unique,
    project_id bigint not null references projects (id) on delete cascade,
    name varchar(255) not null,
    spec jsonb not null,
    spec_hash varchar(64) not null,
    scenario_count integer not null default 0,
    estimated_simulation_seconds double precision not null default 0,
    estimated_budget_seconds double precision not null default 0,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    submitted_at timestamp with time zone
);

create index idx_experiments_project on experiments (project_id);

create table experiment_resources (
    id bigint generated by default as identity primary key,
    experiment_id bigint not null references experiments (id) on delete cascade,
    kind varchar(16) not null,
    reference jsonb not null,
    reference_name varchar(255)
);

create index idx_experiment_resources_experiment on experiment_resources (experiment_id);
create index idx_experiment_resources_name on experiment_resources (reference_name);

-- A trace belongs to an account, not to a project: one library per person, usable from every
-- project they can reach.
--
-- origin is the variant, not a nullable owner. A BUILTIN trace ships with the repository and the
-- SDK's registry resolves it, so it has no owner and no stored bytes; an UPLOADED one has both.
-- The check constraint makes that a rule the database enforces rather than a convention the code
-- is trusted to remember.
--
-- slug is what an experiment document references, so it is unique platform-wide: built-ins are
-- bare ("bitbrains-small") and uploads carry their owner's handle ("alice/nightly-2026"). It may
-- be changed only while no experiment references the trace, which is the same rule that governs
-- deleting one -- a submitted experiment's provenance must keep resolving.
create table traces (
    id bigint generated by default as identity primary key,
    public_id uuid not null unique,
    slug varchar(255) not null unique,
    kind varchar(16) not null,
    origin varchar(16) not null,
    owner_id bigint references users (id) on delete cascade,
    description varchar(1024),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint traces_origin_owner check (
        (origin = 'BUILTIN' and owner_id is null) or (origin = 'UPLOADED' and owner_id is not null)
    )
);

create index idx_traces_owner on traces (owner_id);

-- The bytes of a trace, one row per opendc-trace table it is made of: a workload has tasks and
-- fragments, the other kinds a single table each. Naming a part by its table rather than by a
-- position in a fixed set means a kind that later needs a third table is a change to that kind's
-- table list and nothing here.
--
-- A row exists once the object behind it does, so a trace is ready exactly when it has a part for
-- every table its kind names. The object's key is derived from the trace and the table rather than
-- stored: a browser uploading straight to object storage has to be handed a key before anybody has
-- seen the bytes, which rules out addressing them by their own hash.
create table trace_parts (
    id bigint generated by default as identity primary key,
    trace_id bigint not null references traces (id) on delete cascade,
    table_name varchar(64) not null,
    size_bytes bigint not null,
    row_count bigint,
    unique (trace_id, table_name)
);

-- One row per person a trace has been shared with. A grant governs whether the trace appears in
-- their library and whether they may reference it in a new experiment; it says nothing about
-- experiments already submitted, which pin the content hash.
create table trace_grants (
    id bigint generated by default as identity primary key,
    trace_id bigint not null references traces (id) on delete cascade,
    grantee_id bigint not null references users (id) on delete cascade,
    granted_at timestamp with time zone not null,
    unique (trace_id, grantee_id)
);

create index idx_trace_grants_grantee on trace_grants (grantee_id);

-- The durable work list, written when an experiment is submitted. A unit outlives the executions
-- that carry it: retrying moves it into a new bag, and its own state is the fold the API reports.
-- state is QUEUED (no execution carries it), CARRIED (a live execution does), or terminal.
--
-- total_tasks is written at submit from the document's workload and never again, so progress is read
-- against a denominator that holds still; completed_tasks is what the run reports against it.
create table run_units (
    id bigint generated by default as identity primary key,
    experiment_id bigint not null references experiments (id) on delete cascade,
    scenario_index integer not null,
    seed bigint not null,
    state varchar(16) not null,
    total_tasks integer not null default 0,
    completed_tasks integer not null default 0,
    unique (experiment_id, scenario_index, seed)
);

create index idx_run_units_experiment on run_units (experiment_id);

-- One attempt at running a bag of units together. Created when the work is dispatched rather than
-- when it is submitted, because how it is shaped depends on the slot the dispatcher offers and on
-- what earlier attempts did.
--
-- public_id is what a platform is asked about: it goes into the launch manifest, names the process
-- or job that runs it, and is what cancellation and reconciliation address.
--
-- state is QUEUED (written down), SUBMITTED (handed to the platform), RUNNING (the platform saw it
-- start) or terminal, and every variant column is checked against it: an execution is submitted
-- exactly when it has left the queue, settled exactly when it is terminal, and its platform span
-- and peak memory each name their variant in a kind column rather than in which values are null.
--
-- token_hash is all that is kept of the credential the launcher reports progress with. The secret
-- itself exists only long enough to be written into a manifest, and a fresh one is minted every
-- time the work is handed out, so a token dies with the attempt that carried it. SHA-256 rather
-- than a slow hash: this is a high-entropy secret we generate, not a password somebody chose.
--
-- runtime_multiplier and memory_multiplier are the deployment's corrections the estimates of this
-- attempt were made under, so a calibration read later compares like with like.
create table executions (
    id bigint generated by default as identity primary key,
    public_id uuid not null unique,
    experiment_id bigint not null references experiments (id) on delete cascade,
    state varchar(16) not null,
    attempt integer not null default 1,
    token_hash varchar(64) unique,
    dispatcher varchar(32) not null,
    parallelism integer not null default 1,
    heap_mb integer not null,
    memory_request_mb integer not null,
    time_limit_seconds integer not null,
    estimated_makespan_seconds double precision not null default 0,
    runtime_multiplier double precision not null,
    memory_multiplier double precision not null,
    created_at timestamp with time zone not null,
    submitted_at timestamp with time zone,
    platform_span varchar(16) not null default 'NOT_STARTED',
    platform_started_at timestamp with time zone,
    platform_ended_at timestamp with time zone,
    settled_at timestamp with time zone,
    exit_code integer,
    exit_reason varchar(32),
    exit_message text not null default '',
    peak_memory_kind varchar(16) not null default 'UNMEASURED',
    peak_resident_mb double precision,
    peak_live_heap_mb double precision,
    constraint executions_submitted check (
        (state = 'QUEUED' and submitted_at is null) or (state <> 'QUEUED' and submitted_at is not null)),
    constraint executions_settled check (
        (state in ('SUCCEEDED', 'FAILED', 'CANCELLED') and settled_at is not null and exit_reason is not null and exit_code is not null)
        or (state in ('QUEUED', 'SUBMITTED', 'RUNNING') and settled_at is null and exit_reason is null and exit_code is null)),
    constraint executions_span check (
        (platform_span = 'NOT_STARTED' and platform_started_at is null and platform_ended_at is null)
        or (platform_span = 'STARTED' and platform_started_at is not null and platform_ended_at is null)
        or (platform_span = 'RAN' and platform_started_at is not null and platform_ended_at is not null)),
    constraint executions_live_span check (
        (state not in ('QUEUED', 'SUBMITTED') or platform_span = 'NOT_STARTED')
        and (state <> 'RUNNING' or platform_span = 'STARTED')),
    constraint executions_peak_memory check (
        (peak_memory_kind = 'MEASURED' and peak_resident_mb is not null and peak_live_heap_mb is not null)
        or (peak_memory_kind = 'UNMEASURED' and peak_resident_mb is null and peak_live_heap_mb is null))
);

create index idx_executions_experiment on executions (experiment_id);
create index idx_executions_state on executions (state);
create index idx_executions_settled on executions (settled_at);

-- Which units an attempt carried, what each was expected to cost, and how each one ended. A unit that
-- failed in one execution and succeeded in a later one has a row for each, which is what makes an
-- experiment's retry history readable. The estimates are kept rather than recomputed, so a retry after
-- an out-of-memory kill grows the unit that ran out instead of re-reading the estimate that packed it.
create table execution_units (
    id bigint generated by default as identity primary key,
    execution_id bigint not null references executions (id) on delete cascade,
    unit_id bigint not null references run_units (id) on delete cascade,
    estimated_seconds double precision not null,
    estimated_peak_memory_mb double precision not null,
    state varchar(16) not null,
    exit_reason varchar(32),
    exit_message text not null default '',
    elapsed_seconds double precision,
    unique (execution_id, unit_id),
    constraint execution_units_exit check (
        (state = 'CARRIED' and exit_reason is null and elapsed_seconds is null)
        or (state = 'SUCCEEDED' and exit_reason is not null and elapsed_seconds is not null)
        or (state in ('FAILED', 'CANCELLED') and exit_reason is not null and elapsed_seconds is null))
);

create index idx_execution_units_unit on execution_units (unit_id);

-- cap_kind names the grant ('limited' or 'unlimited') rather than leaving it to be inferred from a
-- null, so an uncapped account is a stated decision. cap_seconds carries the number when limited.
create table budget_windows (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id) on delete cascade,
    period varchar(16) not null,
    used_seconds double precision not null default 0,
    reserved_seconds double precision not null default 0,
    cap_kind varchar(16) not null,
    cap_seconds double precision,
    resets_at timestamp with time zone not null,
    unique (user_id, period)
);

create table invoices (
    id bigint generated by default as identity primary key,
    user_id bigint not null references users (id) on delete cascade,
    issued_at timestamp with time zone not null,
    amount_eur numeric(10, 2) not null,
    paid boolean not null default false
);

-- The workload traces the deployment ships with. Their slugs are bare, with no owner prefix,
-- because they belong to the deployment rather than to a person, and they carry no parts: a named
-- reference resolves under the launcher's trace root, so the bytes come from the repository rather
-- than from object storage.
--
-- The identifiers are written out rather than generated because the generator is spelled
-- differently in each database (random_uuid on H2, gen_random_uuid on PostgreSQL) and this file
-- has to run on both. Fixed ids also mean a built-in keeps the same URL in every deployment.
--
-- kind and origin are upper case because the entity maps them with EnumType.STRING, which matches
-- on the constant's own name. Seeding them lower case parses as no constant at all and fails every
-- read of these rows.
insert into traces (public_id, slug, kind, origin, created_at, updated_at)
values ('6ba7b810-9dad-11d1-80b4-00c04fd430c8', 'bitbrains-small', 'WORKLOAD', 'BUILTIN', current_timestamp, current_timestamp),
       ('6ba7b811-9dad-11d1-80b4-00c04fd430c8', 'surf-week', 'WORKLOAD', 'BUILTIN', current_timestamp, current_timestamp),
       ('6ba7b812-9dad-11d1-80b4-00c04fd430c8', 'surf-month', 'WORKLOAD', 'BUILTIN', current_timestamp, current_timestamp);